import { Injectable, UnauthorizedException, ConflictException, BadRequestException, NotFoundException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { ConfigService } from '@nestjs/config';
import { createHmac } from 'crypto';
import * as bcrypt from 'bcryptjs';
import { PrismaService } from '../../prisma/prisma.service';
import { RegisterDto, LoginDto, VerifyOtpDto } from './dto';
import { OtpService } from './otp.service';

@Injectable()
export class AuthService {
  constructor(
    private prisma: PrismaService,
    private jwtService: JwtService,
    private otpService: OtpService,
    private config: ConfigService,
  ) { }

  async register(dto: RegisterDto) {
    const existingUser = await this.prisma.user.findFirst({
      where: {
        OR: [{ phone: dto.phone }, { email: dto.email }],
      },
    });

    if (existingUser) {
      throw new ConflictException('Phone yoki email allaqachon mavjud');
    }

    const hashedPassword = await bcrypt.hash(dto.password, 10);

    const user = await this.prisma.user.create({
      data: {
        name: dto.name,
        phone: dto.phone,
        email: dto.email,
        password: hashedPassword,
        role: dto.role,
      },
    });

    // Create related profile based on role
    if (dto.role === 'CLIENT') {
      await this.prisma.client.create({
        data: {
          userId: user.id,
          storeName: dto.storeName,
          region: dto.region,
          lat: dto.lat,
          lng: dto.lng,
          // customerCode will be auto-generated by Prisma middleware
        },
      });
    } else if (dto.role === 'DISTRIBUTOR') {
      await this.prisma.distributor.create({
        data: {
          userId: user.id,
          companyName: dto.companyName || 'Company',
          address: dto.address || '',
        },
      });
    } else if (dto.role === 'DRIVER') {
      await this.prisma.driver.create({
        data: {
          userId: user.id,
          vehicleType: dto.vehicleType || '',
          vehicleNumber: dto.vehicleNumber || '',
          licenseNumber: dto.licenseNumber || '',
        },
      });
    }

    const refreshToken = this.generateRefreshToken(user.id, user.role);
    await this.prisma.user.update({ where: { id: user.id }, data: { refreshToken } });

    const token = this.generateToken(user.id, user.role);

    return {
      success: true,
      data: {
        user: this.sanitizeUser(user),
        accessToken: token,
        token: token,
        refreshToken,
      },
    };
  }

  private normalizePhone(phone: string): string {
    const digits = phone.replace(/\D/g, '');
    return digits.startsWith('998') ? `+${digits}` : `+998${digits}`;
  }

  async login(dto: LoginDto) {
    // Faqat berilgan maydonlar bo'yicha qidirish (undefined → OR ni buzadi)
    const conditions: { phone?: string; email?: string }[] = [];
    if (dto.phone) conditions.push({ phone: this.normalizePhone(dto.phone) });
    if (dto.email) conditions.push({ email: dto.email });

    if (conditions.length === 0) {
      throw new UnauthorizedException('Telefon yoki email kiriting');
    }

    const user = await this.prisma.user.findFirst({
      where: { OR: conditions },
      include: {
        client: true,
        distributor: true,
        driver: true,
      },
    });

    if (!user) {
      throw new UnauthorizedException("Telefon/Email yoki parol noto'g'ri");
    }

    const isPasswordValid = await bcrypt.compare(dto.password, user.password);

    if (!isPasswordValid) {
      throw new UnauthorizedException("Telefon/Email yoki parol noto'g'ri");
    }

    if (user.status !== 'ACTIVE') {
      throw new UnauthorizedException('Akkaunt faol emas');
    }

    const refreshToken = this.generateRefreshToken(user.id, user.role);

    await this.prisma.user.update({
      where: { id: user.id },
      data: { lastLogin: new Date(), refreshToken },
    });

    const token = this.generateToken(user.id, user.role);

    return {
      success: true,
      data: {
        user: this.sanitizeUser(user),
        accessToken: token,
        token: token,
        refreshToken,
      },
    };
  }

  async sendOtp(phone: string) {
    const result = await this.otpService.sendOtp(phone);
    return { success: true, message: 'Tasdiqlash kodi Telegram botga yuborildi', ...result };
  }

  async verifyOtpAndRegister(dto: VerifyOtpDto) {
    const isValid = this.otpService.verifyOtp(dto.phone, dto.code);
    if (!isValid) {
      throw new BadRequestException("Kod noto'g'ri yoki muddati tugagan");
    }
    const { code: _code, ...registerData } = dto;
    return this.register(registerData as RegisterDto);
  }

  async refreshAccessToken(refreshToken: string) {
    let payload: any;
    try {
      payload = this.jwtService.verify(refreshToken);
    } catch {
      throw new UnauthorizedException('Refresh token yaroqsiz yoki muddati tugagan');
    }

    const user = await this.prisma.user.findUnique({ where: { id: payload.sub } });
    if (!user || user.refreshToken !== refreshToken) {
      throw new UnauthorizedException('Refresh token topilmadi');
    }

    const newAccessToken = this.generateToken(user.id, user.role);
    return { accessToken: newAccessToken, token: newAccessToken };
  }

  async getMe(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: {
        client: true,
        distributor: true,
        driver: true,
      },
    });

    if (!user) {
      throw new UnauthorizedException('Foydalanuvchi topilmadi');
    }

    return this.sanitizeUser(user);
  }

  // ─── Telegram Mini App — umumiy helper ───────────────────────────────────────

  private async telegramMiniAppAuth(
    initData: string,
    phone: string | undefined,
    requiredRole: 'DRIVER' | 'CLIENT',
  ) {
    const telegramUser = this.validateTelegramInitData(initData);
    if (!telegramUser) throw new UnauthorizedException("Telegram ma'lumotlari noto'g'ri");

    const chatId = String(telegramUser.id);
    let user: any;

    if (phone) {
      const normalizedPhone = this.normalizePhone(phone);
      user = await this.prisma.user.findFirst({
        where: { phone: normalizedPhone },
        include: { client: true, distributor: true, driver: true },
      });
      if (!user) throw new NotFoundException('Bu raqam tizimda topilmadi');
      if (user.role !== requiredRole) {
        const label = requiredRole === 'DRIVER' ? 'haydovchi' : 'do\'kon';
        throw new UnauthorizedException(`Bu raqam ${label} sifatida ro'yxatdan o'tmagan`);
      }
      await this.prisma.telegramChatMapping.upsert({
        where:  { phone: normalizedPhone },
        update: { chatId },
        create: { phone: normalizedPhone, chatId },
      });
    } else {
      const mapping = await this.prisma.telegramChatMapping.findFirst({ where: { chatId } });
      if (!mapping) return { needsPhone: true };
      user = await this.prisma.user.findFirst({
        where: { phone: mapping.phone },
        include: { client: true, distributor: true, driver: true },
      });
      if (!user || user.role !== requiredRole) return { needsPhone: true };
    }

    const refreshToken = this.generateRefreshToken(user.id, user.role);
    await this.prisma.user.update({ where: { id: user.id }, data: { refreshToken } });
    const accessToken = this.generateToken(user.id, user.role);

    return {
      success: true,
      data: { user: this.sanitizeUser(user), accessToken, token: accessToken, refreshToken },
    };
  }

  // ─── Telegram Mini App Auth (Driver & Client) ────────────────────────────────

  async telegramDriverAuth(initData: string, phone?: string) {
    return this.telegramMiniAppAuth(initData, phone, 'DRIVER');
  }

  async telegramClientAuth(initData: string, phone?: string) {
    return this.telegramMiniAppAuth(initData, phone, 'CLIENT');
  }

  private validateTelegramInitData(initData: string): { id: number; first_name: string } | null {
    try {
      const botToken = this.config.get<string>('TELEGRAM_BOT_TOKEN') ?? '';
      if (!botToken || !initData) return null;

      const params = new URLSearchParams(initData);
      const hash = params.get('hash');
      if (!hash) return null;

      params.delete('hash');
      const dataCheckString = Array.from(params.entries())
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => `${k}=${v}`)
        .join('\n');

      const secretKey = createHmac('sha256', 'WebAppData').update(botToken).digest();
      const computed  = createHmac('sha256', secretKey).update(dataCheckString).digest('hex');

      if (computed !== hash) return null;

      // auth_date: 1 soatdan eski initData rad etiladi
      const authDate = Number(params.get('auth_date') ?? '0');
      if (!authDate || Date.now() / 1000 - authDate > 3600) return null;

      const userStr = params.get('user');
      return userStr ? JSON.parse(userStr) : null;
    } catch {
      return null;
    }
  }

  private generateToken(userId: string, role: string): string {
    return this.jwtService.sign({ sub: userId, role });
  }

  private generateRefreshToken(userId: string, role: string): string {
    return this.jwtService.sign({ sub: userId, role, type: 'refresh' }, { expiresIn: '30d' });
  }

  private sanitizeUser(user: any) {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { password, refreshToken, ...sanitized } = user;

    // Add clientId, distributorId, driverId for easier access
    return {
      ...sanitized,
      clientId: user.client?.id || null,
      distributorId: user.distributor?.id || null,
      driverId: user.driver?.id || null,
    };
  }
}
