import { Injectable, UnauthorizedException, ConflictException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import * as bcrypt from 'bcryptjs';
import { PrismaService } from '../../prisma/prisma.service';
import { RegisterDto, LoginDto } from './dto';

@Injectable()
export class AuthService {
  constructor(
    private prisma: PrismaService,
    private jwtService: JwtService,
  ) { }

  async register(dto: RegisterDto) {
    const existingUser = await this.prisma.user.findFirst({
      where: {
        OR: [{ phone: dto.phone }, { email: dto.email }],
      },
    });

    if (existingUser) {
      throw new ConflictException('Phone yoki email allaqachon mavjud');
    }

    const hashedPassword = await bcrypt.hash(dto.password, 10);

    const user = await this.prisma.user.create({
      data: {
        name: dto.name,
        phone: dto.phone,
        email: dto.email,
        password: hashedPassword,
        role: dto.role,
      },
    });

    // Create related profile based on role
    if (dto.role === 'CLIENT') {
      await this.prisma.client.create({
        data: {
          userId: user.id,
          storeName: dto.storeName,
          region: dto.region,
          lat: dto.lat,
          lng: dto.lng,
          // customerCode will be auto-generated by Prisma middleware
        },
      });
    } else if (dto.role === 'DISTRIBUTOR') {
      await this.prisma.distributor.create({
        data: {
          userId: user.id,
          companyName: dto.companyName || 'Company',
          address: dto.address || '',
        },
      });
    } else if (dto.role === 'DRIVER') {
      await this.prisma.driver.create({
        data: {
          userId: user.id,
          vehicleType: dto.vehicleType || '',
          vehicleNumber: dto.vehicleNumber || '',
          licenseNumber: dto.licenseNumber || '',
        },
      });
    }

    const refreshToken = this.generateRefreshToken(user.id, user.role);
    await this.prisma.user.update({ where: { id: user.id }, data: { refreshToken } });

    const token = this.generateToken(user.id, user.role);

    return {
      success: true,
      data: {
        user: this.sanitizeUser(user),
        accessToken: token,
        token: token,
        refreshToken,
      },
    };
  }

  async login(dto: LoginDto) {
    // Email yoki phone orqali foydalanuvchini topish
    const user = await this.prisma.user.findFirst({
      where: {
        OR: [
          { phone: dto.phone },
          { email: dto.email },
        ],
      },
      include: {
        client: true,
        distributor: true,
        driver: true,
      },
    });

    if (!user) {
      throw new UnauthorizedException("Telefon/Email yoki parol noto'g'ri");
    }

    const isPasswordValid = await bcrypt.compare(dto.password, user.password);

    if (!isPasswordValid) {
      throw new UnauthorizedException("Telefon/Email yoki parol noto'g'ri");
    }

    if (user.status !== 'ACTIVE') {
      throw new UnauthorizedException('Akkaunt faol emas');
    }

    const refreshToken = this.generateRefreshToken(user.id, user.role);

    await this.prisma.user.update({
      where: { id: user.id },
      data: { lastLogin: new Date(), refreshToken },
    });

    const token = this.generateToken(user.id, user.role);

    return {
      success: true,
      data: {
        user: this.sanitizeUser(user),
        accessToken: token,
        token: token,
        refreshToken,
      },
    };
  }

  async refreshAccessToken(refreshToken: string) {
    let payload: any;
    try {
      payload = this.jwtService.verify(refreshToken);
    } catch {
      throw new UnauthorizedException('Refresh token yaroqsiz yoki muddati tugagan');
    }

    const user = await this.prisma.user.findUnique({ where: { id: payload.sub } });
    if (!user || user.refreshToken !== refreshToken) {
      throw new UnauthorizedException('Refresh token topilmadi');
    }

    const newAccessToken = this.generateToken(user.id, user.role);
    return { accessToken: newAccessToken, token: newAccessToken };
  }

  async getMe(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      include: {
        client: true,
        distributor: true,
        driver: true,
      },
    });

    if (!user) {
      throw new UnauthorizedException('Foydalanuvchi topilmadi');
    }

    return this.sanitizeUser(user);
  }

  private generateToken(userId: string, role: string): string {
    return this.jwtService.sign({ sub: userId, role });
  }

  private generateRefreshToken(userId: string, role: string): string {
    return this.jwtService.sign({ sub: userId, role, type: 'refresh' }, { expiresIn: '30d' });
  }

  private sanitizeUser(user: any) {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { password, refreshToken, ...sanitized } = user;

    // Add clientId, distributorId, driverId for easier access
    return {
      ...sanitized,
      clientId: user.client?.id || null,
      distributorId: user.distributor?.id || null,
      driverId: user.driver?.id || null,
    };
  }
}
